inchurch/accounts/urls.py
from django.urls import path
from inchurch.accounts import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'


urlpatterns = [

    path('change_pass/', views.change_pass, name='change_pass'),
    path('create_department/', views.create_department, name='create_department'),
    # path('delete_department/', views.delete_department, name='delete_department'),
    path('delete_profile/<int:pk>/', views.delete_profile, name='delete_profile'),
    path('full_profile/', views.full_profile, name='full_profile'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'),  name='logout'),
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('deleted_successfully/', views.deleted_successfully, name='deleted_successfully'),
    path('change_confirmed/', views.change_confirmed, name='change_confirmed'),
    ]

inchurch/urls.py
from django.contrib import admin
from django.urls import path, include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inchurch.accounts.urls'), name='accounts'),
]

templates/base.html
 <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% block head %}
        <title>InChurch - Home</title>
        {% endblock %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
      <body  style="background-color: #50C878">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'accounts:home' %}">InChurch</a>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

             {% if user.is_authenticated %}

                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:full_profile' %}">Profile Detail<span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:update_profile' %}">Update Info</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link disabled" href="{% url 'accounts:change_pass' %}">Change Password</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link disabled" href="{% url 'accounts:delete_profile' user.id %}">Delete Profile</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link disabled" href="{% url 'accounts:create_department' %}">New Department</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link disabled" href="#">Delete Departmment</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link disabled" href="{% url 'accounts:logout' %}">Logout</a>
                  </li>
                </ul>

                  <picture>{{ user.profile_pict }}</picture>   {# Foto usuário #}
                  <h4>Welcome, {{ user.fullname }}!</h4>       {# Nome Completo #}
                  <br/>
                  <h6>Department: {{ user.department }}</h6>  {# Departamento #}

             {% else %}

                 <h2><a href="{% url 'accounts:login' %}">Login</a></h2>     {# Caso usuario não esteja autenticado retorna home com link para a pagina de login #}

             {% endif %}
          </div>
        </nav>

        <div class="content">

            {% block content %}{% endblock %}

        </div>
      </body>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 </html>

templates/change_confirmed.html
{% extends 'base.html' %}


{% block content %}
     <form method="post">
       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             <h1>Changes Confirmed!</h1>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}

templates/change_pass.html
{% extends 'base.html' %}


{% block content %}
     <form method="post">
       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <h4>Change Password</h4>
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             {% csrf_token %}
                             {{ form.as_p }}
                         </div>
                         <button type="submit" class="btn btn-secondary btn-lg btn-block">Submit</button>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}

templates/create_department.html
{% extends 'base.html' %}


{% block content %}
     <form method="post">
       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <h4>New Department</h4>
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             {% csrf_token %}
                             {{ form.as_table }}
                         </div>
                         <br/>
                         <button type="submit" class="btn btn-secondary btn-lg btn-block">Submit</button>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}

templates/delete_department.html
{% extends 'base.html' %}


{% block content %}
      <form method="post">
       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <h4>Delete Department</h4>
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             {% csrf_token %}
                             {{ form.as_p }}
                         </div>
                         <button type="submit" class="btn btn-secondary btn-lg btn-block">Submit</button>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}

templates/delete_profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="text-align: center">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="reset">Submit</button>
        </form>
    </div>
{% endblock %}

templates/deleted_successfully.html
{% extends 'base.html' %}


{% block content %}
     <form method="post">
       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             {% csrf_token %}
                             <h1>Deleted Successfully!</h1>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}

templates/full_profile.html
{% extends 'base.html' %}

{% block content %}
     <form method="post">
       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <h4>Profile Detail</h4>
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             <p>Username: {{ user.fullname }}</p>       {# Nome completo usuario #}
                             <p>Department: {{ user.department }}</p>   {# Departamento usuario #}
                             <p>Email: {{ user.email }}</p>             {# Email usuario #}
                                {% if user.profile_img %}
                                    <img src="{{ user.profile_img.url }}" width="240">      {# Imagem Usuario #}
                                {% endif %}
                         </div>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

templates/login.html
{% load staticfiles %}

<title>InChurch - Login</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


{% block content%}
<body style="background-color: #50C878">
<form method="post">

   <div class="container" style="text-align: center">
         <div class="card card-login mx-auto mt-5">
             <h4>User Login</h4>
             <div class="card-body">
                 <div class="form-group">
                     <div class="form-label-group">
                         {% csrf_token %}
                         {{ form.as_p }}
                     </div>
                     <button type="submit" class="btn btn-secondary btn-lg btn-block">Login</button>
                 </div>
                 <div class="text-center">
                     <a class="d-block small mt-3" href="{% url 'accounts:register' %}">Register an Account</a>
                 </div>
             </div>
         </div>
     </div>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

templates/register.html
{% load staticfiles %}

<title>InChurch - Register</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{% block content%}
    <body style="background-color: #50C878">
    <form method="post">
         <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <h4>User Register</h4>
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">

                              {% csrf_token %}
                              {{ form.as_p }}

                         </div>
                          <button type="submit" class="btn btn-secondary btn-lg btn-block">Register</button>
                     </div>
                     <div class="text-center">
                         <a class="d-block small mt-3" href="{% url 'accounts:login' %}">Login Page</a>
                     </div>
                 </div>
             </div>
         </div>
    </form>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
{% endblock %}

templates/update_profile.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">

       <div class="container" style="text-align: center">
             <div class="card card-login mx-auto mt-5">
                 <h4>Update Profile</h4>
                 <div class="card-body">
                     <div class="form-group">
                         <div class="form-label-group">
                             {% csrf_token %}
                             {{ form.as_p }}
                         </div>
                         <button type="submit" class="btn btn-secondary btn-lg btn-block">Submit</button>
                     </div>
                 </div>
             </div>
         </div>
    </form>
{% endblock %}